### ISSUE TITLE
DB sampleData 입력

### ISSUE THREAD

**Issue by kimmjnha** [breadUniv/breadUnivHTML#6]
- [x] academic_status
- [x] academic_status_list
- [x] admin
- [x] blacklist
- [x] board
- [x] board_category
- [x] cart
- [x] classroom
- [x] comments
- [x] course
- [x] course_drop
- [x] course_drop_list
- [x] course_registration
- [x] credit
- [x] credit_list
- [x] department
- [x] file
- [x] professor
- [x] report_category
- [x] student
- [x] undergraduate
- [x] user
- [x] user_report

**Comment by kimmjnha** [comment]
- [x] course : 컬럼 수정
- [x] course_schedule : 테이블 추가

**Comment by kimmjnha** [comment]
- [x] course_schedule

**Comment by kyeongjinha** [comment]
- [x] Detailed address :  사용자에 상세 주소 추가
